---
Author: Eduárd Czimbalmos
Version: 1551-CNL 113 368, Rev. A
Date: 2014-02-25

---
= Common Protocol module elements for TTCN-3  Toolset with TITAN
:author: Eduárd Czimbalmos
:revnumber: 1551-CNL 113 368, Rev. A
:revdate: 2014-02-25
:toc:

= Functionality

The COMMON Protocol module elements contains definitions in a formalized way, using the standard specification language TTCN-3. This allows to use these definitions in testports, protocol modules, libraries and applications.

The protocol module uses Titan’s RAW encoding attributes <<_3, [3]>> and hence is usable with the Titan test toolset only.

== Implemented Protocols

None.

=== Modified and Non-Implemented Protocol Elements

None.

=== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* Titan TTCN-3 Test Executor version CRL 113 200 R7A (1.7.pl0) or higher installed. For Installation Guide see <<_2, [2]>>.

NOTE: This version of the test port is not compatible with Titan releases earlier than CRL 113 200 R7A.

= Usage

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor; however, to make the work more efficient a TTCN3enabled text editor is recommended (for example `nedit`, `xemacs`). Since the GTPv2 PrivateExtensions protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<_2, [2]>>.

== Configuration

None.

== Examples

None.

= Interface description

None.

= Change information

== R7A

`record of` and `set of` type definitions have been added to the `General_Types` module in order to give type compatibility within TTCN-3 source codes.

= Terminology

None.

== Abbreviations

TTCN-3:: Testing and Test Control Notation version 3

= References

[[_1]]
[1] ETSI ES 201 873-1 v4.5.1 (2013-04) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] User Guide for TITAN TTCN-3 Test Executor

[[_3]]
[3] Programmer’s Technical Reference for Titan TTCN–3 Test Executor

